### ISSUE TITLE
Add bLS and wind tunnel data processing

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/Hafner-2023-bls-wt-comp#5]
@J-Kamp reminder to add your scripts

**Comment by J-Kamp** [comment]
Hi @sashahafner 
I've added my stuff, I think. There need to be an addition to the README.
Let me know what I should do.

**Comment by J-Kamp** [comment]
Done

**Comment by sashahafner** [comment]
Just so we have it here: we cannot upload data files because they are too big (>100MB). 
But we still opted to include scripts.
So users cannot actually repeat the calculations but at least they and we can check settings and more details about how calculations were done.

**Comment by sashahafner** [comment]
@J-Kamp can you check README.md around lines 25 and 65?
I changed directory names a bit.

**Comment by sashahafner** [comment]
@JohannaPedersen we should add whatever we can fit of your wind tunnel data processing as well.

**Comment by sashahafner** [comment]
Done.
See scripts-bLS and scripts-wt
